defaults:
  - _self_
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none

hydra:
  output_subdir: null
  run:
    dir: .
  job_logging:
    root:
      handlers: []

GENERAL:
  total_step: 1000000
  log_step: 10
  checkpoint_step: 1000
  warmup_step: 5000
  num_worker: 4
  prefetch_factor: 2
  seed: 3229084

TRAIN:
  lr: 1e-5
  backbone_lr: 1e-7
  grad_accum_step: 1
  max_grad: 5.0
  weight_decay: 1e-4
  sample_per_device: 90
  expansion_ratio: 1.1
  scale_z_range: [0.7, 1.3]
  scale_f_range: [0.8, 1.2]
  persp_rot_max: 0.2617993877991494 # pi/12

DATA:
  source: [
    /mnt/qnap/data/datasets/webdatasets/InterHand2.6M/train/*,
    /mnt/qnap/data/datasets/webdatasets/DexYCB/s1/train/*,
    /mnt/qnap/data/datasets/webdatasets/HO3D_v3/train/*
  ]
  stride: 1

MODEL:
  img_size: 224
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
  stage: stage1
  num_frame: 1
  backbone:
    backbone_str: model/facebook/dinov2-base
    infusion_layer: [2, 6, 10]
    drop_cls: false
  hand_feat_extractor:
    num_layer: 3
    num_head: 12
    dim_head: 64
    dim_mlp: 1024
    dropout: 0.0
    norm: layer
    context_dim: 768
    skip_token_embed: true
  persp_info_embed:
    num_sample: 16
    pie_fusion: "cls"
  temporal_encoder:
    num_layer: 2
    num_head: 12
    trope_scalar: 20.0
    zero_linear: true
  detokenizer:
    joint_type: "3"

LOSS:
  kps3d_loss_type: "l1"
  verts_loss_type: "l1"